export const Player = Object.freeze({
  WIDTH: 16,
  HEIGHT: 32,
  RUN_ACCELERATION: 2,
  FLY_ACCELERATION: 1.5,
  MAX_GROUND_SPEED: 66,
  MAX_JUMP_SPEED: 200,
  // http://style.org/unladenswallow/
  MAX_AIR_SPEED: 300,
  MAX_JUMP_INTENSITY: 2 ** 8 - 1,
  JUMP_INTENSITY_DIMINISHMENT_FACTOR: 20,
  GROUND_FRICTION: 80,
  AIR_FRICTION: 0,
});
