name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    uses: denoland/setup-deno@v1
    with:
      deno-version: v1.30

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build client
        run: ./scripts/build-client.sh

      - name: Build server
        run: ./scripts/build-server.sh

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "rtmp-web"
          entrypoint: "./server/mod.ts"
          root: dist
